CREATE TABLE products (id SERIAL PRIMARY KEY ,name VARCHAR(100) NOT NULL UNIQUE, price INTEGER NOT NULL,category VARCHAR(50) NOT NULL);
CREATE TABLE users (id SERIAL PRIMARY KEY ,first_name VARCHAR(100) UNIQUE NOT NULL, last_name VARCHAR(100) NOT NULL, passs VARCHAR(255) UNIQUE NOT NULL);
CREATE TABLE orders (id SERIAL PRIMARY KEY ,user_id INTEGER  REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE, status VARCHAR(50) NOT NULL);
CREATE TABLE orders_products (id SERIAL PRIMARY KEY ,order_id INTEGER  REFERENCES orders(id) ON DELETE CASCADE ON UPDATE CASCADE,product_id INTEGER  REFERENCES products(id) ON DELETE CASCADE ON UPDATE CASCADE ,quantity integer NOT NULL);
 

